default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Docker Composeのサービス名「db」を指定
  host: <%= ENV.fetch("DATABASE_HOST") { "db" } %>
  username: postgres
  password: password

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test